/* (c) https://github.com/MontiCore/monticore */
package de.monticore.lang.sdbasis._symboltable;

import de.monticore.lang.sdbasis._ast.ASTSDObject;
import de.monticore.lang.sdbasis.types.FullSDBasisSynthesizer;
import de.monticore.prettyprint.IndentPrinter;
import de.monticore.symbols.basicsymbols._symboltable.VariableSymbol;
import de.monticore.symbols.oosymbols._symboltable.OOTypeSymbol;
import de.monticore.types.check.SymTypeExpression;
import de.monticore.types.check.SymTypeExpressionFactory;
import de.monticore.types.check.TypeCheckResult;
import de.monticore.types.mcbasictypes._ast.ASTMCObjectType;
import de.monticore.types.prettyprint.MCBasicTypesFullPrettyPrinter;
import de.se_rwth.commons.logging.Log;

import java.util.Optional;

public class SDBasisScopesGenitor extends SDBasisScopesGenitorTOP {

  private final FullSDBasisSynthesizer synthesizer = new FullSDBasisSynthesizer();

  /**
   * prettyPrinter used for error reporting.
   */
  private final MCBasicTypesFullPrettyPrinter prettyPrinter = new MCBasicTypesFullPrettyPrinter(new IndentPrinter());

  /* generated by template core.Constructor*/
  public SDBasisScopesGenitor() {
    super();
  }

  @Override
  public void endVisit(ASTSDObject node) {
    VariableSymbol symbol = node.getSymbol();

    if (node.isPresentMCObjectType()) {
      ASTMCObjectType objectType = node.getMCObjectType();

      final TypeCheckResult typeResult = synthesizer.synthesizeType(objectType);
      if (!typeResult.isPresentResult()) {
        Log.error(String.format("0xB0005: The type (%s) of the object (%s) could not be calculated", prettyPrinter.prettyprint(objectType), node.getName()));
      }
      else {
        symbol.setType(typeResult.getResult());
      }
    }
    else {
      OOTypeSymbol objectType = new OOTypeSymbol("Object");
      symbol.setType(SymTypeExpressionFactory.createTypeExpression(objectType));
    }
  }
}
