# (c) https://github.com/MontiCore/monticore

image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

cache:
  paths:
    - .gradle/wrapper
  key: ${CI_COMMIT_REF_SLUG}

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - mirror

githubmirror:
  image: maven:3-jdk-8
  stage: mirror
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SE_CIBUILD_SSH_PRIV_KEY")
    - echo "$SE_CIBUILD_SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
    - git config --global user.email "noreply-ci@se-rwth.de"
    - git config --global user.name "MontiCore Mirroring Bot"
    - mkdir -p ~/.ssh
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script: 
    - sh pre/mirror.sh
    - cd ..
    - "if [ -d \"sequence-diagram\" ]; rm -r sequence-diagram; fi"
    - git clone git@github.com:MontiCore/sequence-diagram.git
    - rm -r sequence-diagram/*
    - mv sd-language/* sequence-diagram/
    - cd sequence-diagram 
    - git add --all
    - git commit -m 'Updated branch with most recent version.'
    - git push --force origin master
    - cd ..
    - rm -r sequence-diagram
    - exit 0
  only:
    - dev
