mavenUser=${username}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

useLocalRepo=false

mc_version=7.10.0-SNAPSHOT
version=7.10.0-SNAPSHOT

commons_version=7.10.0-SNAPSHOT
commons_cli_version=1.11.0
shadow_plugin_version=8.3.9
junit_version=6.0.3


