mavenUser=${username}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
mc_version=7.9.0-SNAPSHOT
version=7.9.0-SNAPSHOT
commons_version=7.9.0-SNAPSHOT
shadow_plugin_version=7.1.2
useLocalRepo=false


